export default {
  signedup: "You signed up successfully",
  emailConfirmation:"A verification email has been sent to ",
  accountVerified:"The account has been verified. Please log in.",
  userVerification:"This user has already been verified.",
  signedIn: "User logged in successfully",
  passwordReset:"The link to reset password sent succesfully to your email!",
  passwordUpdated:"Password updated succesfully!",
  resend:"Confirmation email resend succesfully!",
  loggedin:"Successfully logged in",
  requestedUser:"Requested user",
  profileUpdated:"Profile updated succesfully!",
  passwordChanged:"Password changed succesfully!",
  allRolePermissions:"All roles Permissions",
  RolePermissionCreated:"Role_permission permission created",
  RolePermissionRetreived:"Successfully retrieved Role_permission",
  RolePermissionUpdated:"Role_permission updated successfully",
  RolePermissionDeleted:"Role_permission successfuly deleted",
  AllRoles:"all roles",
  RoleCreated:"Role created",
  RoleRetreived:"Successfully retrieved Role",
  RoleUpdated:"Role updated successfuly",
  RoleDeleted:"Role deleted successfully",
  PermissionCreated:"Permission created",
  AllPermissions:"All permissions",
  PermissionRetreived:"Successfully retrieved permission",
  permissionUpdated:"Permission updated successfuly",
  PermissionDeleted:"Permission deleted successfully",
  BusinessCategoryCreated:"Business category Created",
  allBusinessCategories:"All business categories",
  BusinessCategoryRetreived:"Successfully retrieved business category",
  BusinessCategoryUpdated:"The category updated successfully",
 BusinessCategoryDeleted: "The category has been deleted successfully! ",
 stateRemember:'your profile will be remembered on your next request initiation',
 stateNotRemember:'your profile will not be remembered on your next request initiation'


}